### ISSUE TITLE
Unable to set Robots meta tag.

### ISSUE THREAD

**Issue by omarreiss** [Yoast/yoast-seo-for-magento2#22]
In the TYPO3 and WP extensions we have the ability to set a Robots meta. In TYPO3 that looks like this:

<img width="906" alt="screen shot 2017-04-05 at 12 43 57" src="https://cloud.githubusercontent.com/assets/1488816/24702118/b3064a6a-19fd-11e7-9487-45167a69932e.png">

This is still missing from the Magento extension. Please refer to the product sheet for the out of the box technical SEO features we expect the module to provide: https://github.com/Yoast/wordpress-seo/wiki/Yoast-SEO-product-sheet#technical-seo-out-of-the-box

**Comment by vincenthornikx** [comment]
magento generates sensible default robots instructions based on settings.
