### ISSUE TITLE
Some special characters get stripped out in the focus keyword field

### ISSUE THREAD

**Issue by benvaassen** [Yoast/Yoast-SEO-for-Magento2#3]
The string `(/*-+_@&$#%)` restuls in: `/-_@&#%`

See the screenshot:

![home_page___pages___elements___content___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22459132/ad6a7dfa-e79f-11e6-82c7-decb5f748012.png)

**Comment by lukvdborne** [comment]
@tacoverdo @omarreiss it appears this is being caused by the following line in the YoastJS lib: 

`return a = a.replace(/[\[\]\{\}\(\)\*\+\?\^\$\|]/g, ""), a = d(a), a = e(a)`

Is this expected behaviour or can the stripping of characters be limited a bit more?

**Comment by haassie** [comment]
@lukvdborne In the TYPO3 plugin I don't have this issue. Are you using an up to date version of the library of Yoast SEO?

![screen shot 2017-05-09 at 10 11 23](https://cloud.githubusercontent.com/assets/11075733/25841314/e3b7052a-349f-11e7-9da0-f5ce62c4ecdb.png)

**Comment by lukvdborne** [comment]
@vincenthornikx kun jij naar de lib kijken? Deze lijkt nog van oktober te zijn.

**Comment by haassie** [comment]
Staat de nieuwe versie nu op de demo omgeving @lukvdborne ?

**Comment by lukvdborne** [comment]
@haassie deze heb ik zojuist klaargezet in PR.

**Comment by haassie** [comment]
Dit probleem is nu opgelost
