### ISSUE TITLE
error to compile magento 2.15

### ISSUE THREAD

**Issue by psapoznik** [Yoast/Yoast-SEO-for-Magento2#30]
php magento setup:di:compile

error:
 MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
        MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates
                Incorrect dependency in class MaxServ\YoastSeo\Block\Adminhtml\Config\Form\Field\AnalysisTemplates in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/Config/Form/Field/AnalysisTemplates.php
\Magento\Framework\Math\Random already exists in context object
        MaxServ\YoastSeo\Block\YoastSeo
                Incorrect dependency in class MaxServ\YoastSeo\Block\YoastSeo in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php
\Magento\Framework\App\RequestInterface already exists in context object
Total Errors Count: 2

**Comment by vincenthornikx** [comment]
Thank you for your feedback. We will fix this as soon as possible.

**Comment by vincenthornikx** [comment]
Fixed in v1.0.1
