### ISSUE TITLE
error 500 Uncaught Error: Call to a member function getMetaProvider()

### ISSUE THREAD

**Issue by psapoznik** [Yoast/Yoast-SEO-for-Magento2#32]
[23-May-2017 13:24:04 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getMetaProvider() on boolean in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php:116
Stack trace:
#0 /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/view/frontend/templates/yoastseo.phtml(27): MaxServ\YoastSeo\Block\YoastSeo->getMeta()
#1 /home/klevershop/public_html/comprarbici/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/kleversho...')
#2 /home/klevershop/public_html/comprarbici/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(MaxServ\YoastSeo\Block\YoastSeo), '/home/kleversho...', Array)
#3 /home/klevershop/public_html/comprarbici/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/home/kleversho...')
#4 /home/klevershop/public_html/comprarbici/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\ in /home/klevershop/public_html/comprarbici/vendor/maxserv/magento-module-yoastseo/Block/YoastSeo.php on line 116

**Comment by lukvdborne** [comment]
Hello @psapoznik,

When/where are you getting that a error?

**Comment by psapoznik** [comment]
In error.log, and enter the web.

**Comment by vincenthornikx** [comment]
Could you specify which layout handle is being rendered / should be rendered on the page where you get this error?
