### ISSUE TITLE
getting error of contentType requried for content in magento 2 Edit products 

### ISSUE THREAD

**Issue by geetkamal** [Yoast/Yoast-SEO-for-Magento2#34]
We have configured this module,  but After enabling we are getting one Error in back end  site - while add / edit products 

contentType is required for 'content' ? 

can you please help to fix this ?

**Comment by Aaron-Lewis** [comment]
Hi. 
Installed Yoast extension on a Magento 2 site and experiencing the same issue. When editing products in M2 admin i get following ComponentType error.

Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "componentType" is a required for "container_url_key" component.

If Yoast extension is deactivated then errors no longer appear. Could you please help to find a solution.

**Comment by vincenthornikx** [comment]
Could you please post the full error log?

**Comment by Aaron-Lewis** [comment]
Hi Vincenthornikx. 
Attached is full error I see when Edit is clicked in M2 admin. Let me know if you need anything else.

[Edit Product error log.txt](https://github.com/Yoast/Yoast-SEO-for-Magento2/files/1084623/Edit.Product.error.log.txt)

**Comment by vincenthornikx** [comment]
Can you confirm that you have the SEO attributes in your attribute set? The following attributes must be in the Search Engine Optimatization group of your attribute set:
- url_key
- meta_title
- meta_description
- meta_keyword
- focus_keyword (created by module)
- yoast_robots_instructions (created by module)

**Comment by vincenthornikx** [comment]
Did my previous comment help you and/or fix your problem?

**Comment by Yihka** [comment]
Hello,

@vincenthornikx 

I'd like to report the exact same problem. I've traced the error and it seems to be related to the following code:

/Ui/Catalog/DataProvider/Product/Form/Modifier/YoastSEO - setYoastFieldClasses - $meta['content']['children']['container_description']['children']['description']['arguments']['data']['config']['additionalClasses'] = 'yoastBox-content'; - Line 126

Commenting this out lets me load the page.

---

I do have the SEO attribute set configured correctly. I am using Magento 2.1.7.

**Comment by geetkamal** [comment]
Hello,

Thanks for the update, but what is the purpose of that line . Also I am
getting the Design of Edit product pages messed up

Facebook and Twitter input fields displayed outside of tab panel - Yoast
SEO . So please help me to fix this issue as well .

**Comment by Yihka** [comment]
Hey,

I don't know what it does, apart from adding a class to something with HTML. Just pointing out what is causing the issue so the developers can look at it

**Comment by vincenthornikx** [comment]
Hi @geetkamal ,
The layout should be fixed in the latest release: 1.0.3

**Comment by vincenthornikx** [comment]
Hi @Yihka ,
Can you confirm that you have the 'description' attribute in the 'content' group in your attribute set?

**Comment by Yihka** [comment]
Hello @vincenthornikx ,

'description' falls under 'Content', for custom attribute sets. The 'default' attributeset has it under 'product details'.

**Comment by vincenthornikx** [comment]
patch release 1.0.5 should fix this issue

**Comment by royvanos** [comment]
This works like a charm now!

**Comment by geetkamal** [comment]
Thanks for the update,
