### ISSUE TITLE
meta property="go:url" Adds Slug for Home Page

### ISSUE THREAD

**Issue by dankocrama980** [Yoast/Yoast-SEO-for-Magento2#35]
For the home page of a website The module adds the slug to the meta property="go:url"

Now 

`<meta property="og:url" content="https://www.magentowebsite.com/home">`

Should be 

`<meta property="og:url" content="https://www.magentowebsite.com/">`

**Comment by vincenthornikx** [comment]
Fixed in version 1.0.2
