### ISSUE TITLE
500 - internal server error when trying to add new product

### ISSUE THREAD

**Issue by hezide** [Yoast/Yoast-SEO-for-Magento2#36]
I Have installed the module but I get 500 when trying to add a new product.
Disabled the module and it works fine...

**Comment by vincenthornikx** [comment]
Hello @hezide 
Could you check your apache error logs. It looks like your server is configured to return a 500 status error when encoutering PHP errors.
Please add any relevant error messages to this issue.

**Comment by hezide** [comment]
I think it's this one:
[Mon Jul 03 02:29:48 2017] [error] [client 87.76.17.16] client denied by server configuration: /home/minimoon/ochosbags.com/html/app/etc/config.php

should I contact my hosting provider? what should I ask them exactly?

thanks

**Comment by hezide** [comment]
this is the error:

> "==> var/log/debug.log <==
[2017-07-04 19:27:24] main.DEBUG: cache_invalidate:  {"method":"POST","url":"https://ochosbags.com/minimoon_admin/admin/index/index/key/b420b444796b9e3f0d9e6ad3049b4d972dd6131fff6f56e1e414c15f2ab7615a/","invalidateInfo":{"tags":["BACKEND_MAINMENU"],"mode":"matchingAnyTag"},"is_exception":false} []

==> ../../var/ochosbags.com/logs/error.log <==
[Tue Jul 04 15:27:26 2017] [error] [client 87.76.17.16] client denied by server configuration: /home/minimoon/ochosbags.com/html/app/etc/config.php

==> ../../var/php-fpm/error.log <==
[04-Jul-2017 19:31:54 UTC] PHP Fatal error:  Uncaught Error: Call to a member function count() on null in /chroot/home/minimoon/ochosbags.com/html/vendor/maxserv/magento-module-yoastseo/Model/EntityConfiguration/Catalog/Product/ImageProvider.php:56
Stack trace:
#0 /chroot/home/minimoon/ochosbags.com/html/vendor/maxserv/magento-module-yoastseo/Helper/Analysis/TemplatesHelper.php(121): MaxServ\YoastSeo\Model\EntityConfiguration\Catalog\Product\ImageProvider->getImages()
#1 /chroot/home/minimoon/ochosbags.com/html/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/YoastBox/Config.php(95): MaxServ\YoastSeo\Helper\Analysis\TemplatesHelper->getImages('catalog_product')
#2 /chroot/home/minimoon/ochosbags.com/html/vendor/maxserv/magento-module-yoastseo/Block/Adminhtml/YoastBox/Config.php(71): MaxServ\YoastSeo\Block\Adminhtml\YoastBox\Config->getImages()
#3 /chroot/home/minimoon/ochosbags.com/html/var/view_preprocessed/html/vendor/maxserv/magento-module-yoastseo/view/adminhtml/templates/yoastbox/config.phtml(2): MaxServ\YoastSeo\Block\Adminhtml\YoastBox\Conf in /chroot/home/minimoon/ochosbags.com/html/vendor/maxserv/magento-module-yoastseo/Model/EntityConfiguration/Catalog/Product/ImageProvider.php on line 56".

>

**Comment by vincenthornikx** [comment]
@hezide should be fixed in the next patch version

**Comment by hezide** [comment]
Ok thanks, when it's released I'll test it..

**Comment by vincenthornikx** [comment]
Patch version has been released
