### ISSUE TITLE
Meta description isn't recognized correctly with special characters

### ISSUE THREAD

**Issue by benvaassen** [Yoast/Yoast-SEO-for-Magento2#4]
For example, with the string `(/*-+_@&$#%)`, see screenshot: 

![home_page___pages___elements___content___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22460624/02085f5c-e7a6-11e6-8e6e-83a58ed1ad11.png)

**Comment by benvaassen** [comment]
Related: #3

**Comment by haassie** [comment]
Dit probleem is nu opgelost
