### ISSUE TITLE
Yoast product attributes are orphaned until the admin clicks on "Yoast SEO"

### ISSUE THREAD

**Issue by jantzenw** [Yoast/Yoast-SEO-for-Magento2#40]
## Prerequisite
1. Magento 2.1.6
2. YoastSEO 1.0.1

## Steps to reproduce
1. Navigate to a product.
2. Scroll down and see that the Facebook and Twitter SEO product attributes are orphaned under the Gift Options tab with no heading.
3. Click on Yoast SEO.
4. See that these fields pop into the Yoast SEO settings under the Facebook and Twitter sections. 

## Video demonstration
https://www.screencast.com/t/O4VEjkf7

**Comment by vincenthornikx** [comment]
Hi @jantzenw,
Please update to the latest version and redeploy your static files. This has already been fixed.
