### ISSUE TITLE
no option for a unique store view meta description

### ISSUE THREAD

**Issue by hezide** [Yoast/Yoast-SEO-for-Magento2#41]
I have written a meta description in the default store view, and then went to a specific store view.
I have the option of "Use Default Value" for the focus keyword and it works, but no such option for the "SEO title", "Slug" and "Meta description".

**Comment by vincenthornikx** [comment]
Hi @hezide, I will check this. This may have been something I overlooked.

**Comment by hezide** [comment]
Great, thanks!

**Comment by hezide** [comment]
Looks like it's the same for category pages.

**Comment by hezide** [comment]
any update? all store view takes the same meta description and seo title from default...

**Comment by vincenthornikx** [comment]
Hi @hezide,
Is it okay if the 'use default' checkbox is implicitly unchecked when you change the value on store level? The meta title and meta description field are hidden and synchronised with the snippet preview editor so the magento native fields will not be visible.

**Comment by hezide** [comment]
I guess it should be ok.
Right now it's very messy: I can't change meta title even in store view so I  will test this change.

is it ready to update yet?

**Comment by hezide** [comment]
Also, it seems that "Create Permanent Redirect for old URL" does not exist therefore every change in URL is not redirected...

for the meantime, I will use original search engine optimization options.

**Comment by vincenthornikx** [comment]
Hi @hezide I've added the 1.0.4 patch release which addresses this issue. I'm still working on the 'Create Permanent Redirect' so that is not yet fixed in this release.

**Comment by vincenthornikx** [comment]
fixed in 1.0.4 (redirect checkbox is fixed in 1.0.5)
