### ISSUE TITLE
Mass-action page gives error

### ISSUE THREAD

**Issue by rikwillems** [Yoast/Yoast-SEO-for-Magento2#42]
When I try to do a mass-action on products the page where you normally fill the attributes gives an error:

PHP Fatal error:  Uncaught Error: Class 'fileUploader' not found in vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:93

Because this frontend model is only set for Yoast attributes I report it as an issue here.

**Comment by hezide** [comment]
same here, this is what I get:

> Products Information
Attributes Changes have been made to this section that have not been saved. This tab contains invalid data. Please resolve this before saving.

**Comment by Tjitse-E** [comment]
@rikwillems @hezide, i've got the same problem with maxserv/magento-module-yoastseo v1.0.5 and Magento 2.1.9

You can change the `frontend_input` in the database from 'fileUploader' to 'image'. This has solved the problem for me, the upload functionality still works, as well as the mass updates.

![31623544-0809c132-b2a0-11e7-8c0f-dfa602fe6fb6](https://user-images.githubusercontent.com/14849044/31623555-1191a490-b2a0-11e7-9937-e11f2cfee87c.png)

**Comment by vincenthornikx** [comment]
Thanks @Tjitse-E for the pull request. I've merged this and added the 1.0.6 patch release which fixes this issue.
