### ISSUE TITLE
Uncaught Error: Call to a member function getLoadedProductCollection()

### ISSUE THREAD

**Issue by MMcConn** [Yoast/Yoast-SEO-for-Magento2#43]
Magento 2.1.7
CentOS 7
PHP 7.0.17

Fatal error: Uncaught Error: Call to a member function getLoadedProductCollection() on boolean in /var/www/html/magento2/app/code/MaxServ/YoastSeo/Model/EntityConfiguration/Catalog/Category/MetaProvider.php:127 Stack trace: #0 /var/www/html/magento2/app/code/MaxServ/YoastSeo/Model/EntityConfiguration/Catalog/Category/MetaProvider.php(147): MaxServ\YoastSeo\Model\EntityConfiguration\Catalog\Category\MetaProvider->getToolbarBlock() #1 /var/www/html/magento2/app/code/MaxServ/YoastSeo/view/frontend/templates/yoastseo.phtml(42): MaxServ\YoastSeo\Model\EntityConfiguration\Catalog\Category\MetaProvider->getPrevLink() #2 /var/www/html/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/www/html/every...') #3 /var/www/html/magento2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(MaxServ\YoastSeo\Block\YoastSeo), '/www/html/every...', Array) #4 /var/www/html/magento2/vendor/magento/framework/View/Element/Te in /var/www/html/magento2/app/code/MaxServ/YoastSeo/Model/EntityConfiguration/Catalog/Category/MetaProvider.php on line 127

This occurs only on category front pages -- IE: 
www.examplestore.com/example-category.html

The home page, product pages and checkout all seems to work fine, but if we create a category specific page to display products in the category it throws the above exception.

**Comment by larsroettig** [comment]
Hi @MMcConn, it is possible you remove or rename **category.products.list** Block ?
The Yoast Team try to load the Block but Magento 2 will return false if Block is unfined. 

https://github.com/Yoast/Yoast-SEO-for-Magento2/blob/master/Model/EntityConfiguration/Catalog/Category/MetaProvider.php#L124

Best regards,

Lars
--------------------------
Member of the Community Engineering at Magento

**Comment by MMcConn** [comment]
Apologies for the delay in response, we had an issue with our store that required some work and this took a back seat.

I've not removed or renamed category.product.list, but perhaps the theme we purchased is handling category pages in a way that is not best practice?

**Comment by MMcConn** [comment]
Thank you for pushing me in the right direction, I dug into this a little deeper and one of the plugins that came with the them we installed (SM Market > SM_ShopBy) was removing the category.products.list, and replacing it with a block named "product_list".

As this could happen with any custom theme, is it possible to add a configuration in the magento admin that defaults to category.products.list, but allows you to define an alternate product list option for category pages? 

For now, I've modified the code to point to the correct list and Yoast is back up and running on our Dev environment.  After a little more testing we'll like push it to production shortly.

**Comment by larsroettig** [comment]
@MMcConn no problem you are welcome I can add to core team slack if you problems than you write me a message. 

Twitter: https://twitter.com/LarsRoettig

Best regards 

Lars

--------------------------
Member - Community Engineering Team at Magento

**Comment by MMcConn** [comment]
Lars, that would be great.  I'll close out this issue.  

Thanks,

Mark
