### ISSUE TITLE
SEO-tool werkt niet correct.

### ISSUE THREAD

**Issue by Become1** [Yoast/Yoast-SEO-for-Magento2#49]
Ik loop steeds tegen een probleem aan bij het maken van de SEO optie in Magento 2.

- Bij het aanmaken van een categorie of product pagina, kan ik de SEO titel zonder problemen invoeren. Na opslaan van de pagina blijft deze ook staan.

**CATEGORIE PAGINA**

1. Op de categorie pagina, word de meta description na het opslaan, de eerste keer niet meegenomen. Vervolgens dien je nogmaals de meta description in te voeren, bij de tweede keer opslaan word de content wel bewaard.
2. De slug word helemaal niet bewaard, hoe vaak je die ook invoert. Daar komt bij dat na de derde  keer opslaan van de slug, de meta description wederom leeg is.

Resume
- Eerste keer opslaan SEO title + Slug + Meta description, alleen de SEO title word opgeslagen.
- Tweede keer opslaan SEO title + Slug + Meta description, de SEO title + Meta description word opgeslagen.
- Derde keer opslaan SEO title + Slug + Meta description, alleen de SEO title word weer opgeslagen.

**PRODUCT PAGINA**
Hier kan heb ik alleen problemen met de slug, deze krijg je niet toegevoegd. Telkens als je opslaat word de slug vervangen door example-post/

Goed om te weten, als ik een csv product import maak, word de slug wel opgeslagen. Als je vervolgens het product opent en een aanpassing maakt in een ander onderdeel, bijvoorbeeld general settings, word de slug weer 

**_Bijgevoegd twee schermafbeeldingen._**
_1. Invoeren van de SEO gegevens.
2. Resultaat na opslaan._

![schermafbeelding 2017-09-28 om 13 55 14](https://user-images.githubusercontent.com/31471754/31053100-e10f0fb2-a695-11e7-93a7-53d2556210be.png)
![schermafbeelding 2017-09-28 om 13 55 45](https://user-images.githubusercontent.com/31471754/31053099-e10f12e6-a695-11e7-9c5c-19053191e658.png)

vervangen door example-post/ na opslaan.

**Comment by vincenthornikx** [comment]
Hoi @Become1 
Welke versie van de module gebruik je? Ik heb zoiets bij mij ook voorbij zien komen maar dat is in een van de laatste patch versies opgelost. De laatste versie is 1.0.5

**Comment by Become1** [comment]
Hoi @vincenthornikx 
Wij gebruiken nu versie 1.0.3. Ik zal upgraden naar de laatste versie en laten weten wat het resultaat is.

**Comment by Become1** [comment]
@vincenthornikx 

Helaas is het probleem na upgraden niet opgelost.

**Comment by vincenthornikx** [comment]
@Become1 binnenkort komt versie 2.0 uit, als het goed is is het probleem hier in opgelost.

**Comment by vincenthornikx** [comment]
@Become1 versie 2.0.0 is zojuist gereleased. Het probleem komt hier (bij mij) niet meer in voor.
