### ISSUE TITLE
The webshop url is shown automatically after the meta title.

### ISSUE THREAD

**Issue by EsteraVendic** [Yoast/Yoast-SEO-for-Magento2#50]
After filling in the meta title for category pages in the backend, the url of the webshop is shown after the title on the webshop. I checked it with the Moz toolbar extension.

In the example below you can see the difference. Is this a functionality in the Yoast module? If yes, where can I adjust it?

![__category_meta_templates___magento_admin_nl_2_png_en_huissteden_naaimachines_huissteden_nl_png_en___category_meta_templates___magento_admin_huissteden_nl](https://user-images.githubusercontent.com/30499229/31228211-f0470058-a9dc-11e7-95a4-37cb05277bc2.png)

**Comment by vincenthornikx** [comment]
Hi @EsteraVendic are you using a different extension for these meta templates? This is not a feature of the YoastSEO extension.

**Comment by EsteraVendic** [comment]
Hi @vincenthornikx, Yes we use the BSS Commerce Meta tags template. As you described, it's not a YoastSEO feature. Thank you for the information.
