### ISSUE TITLE
Yoast SEO not visible after installation

### ISSUE THREAD

**Issue by kroonwebdesign** [Yoast/Yoast-SEO-for-Magento2#52]
Hello,

After installation the Module is not visible within the backend. (After deleting cache / reindex etc)
Anyone with the same issue?

Kind regards,

[xxxx@server public_html]$ composer config repositories.magento-module-yoastseo '{"type": "vcs", "url": "git@github.com:Yoast/magento-seo.git"}'

[xxxx@server public_html]$ composer require maxserv/magento-module-yoastseo
Using version ^1.0 for maxserv/magento-module-yoastseo
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)         Nothing to install or update
Generating autoload files

**Comment by vincenthornikx** [comment]
Hi @kroonwebdesign , it seems that the module has not been installed. Could you post your entire composer.json file?

**Comment by kroonwebdesign** [comment]
Hi @vincenthornikx,

Is installed now, cache issue:)

Thanks!
