### ISSUE TITLE
"Base table or view not found" error on setup:upgrade

### ISSUE THREAD

**Issue by pooshok** [Yoast/Yoast-SEO-for-Magento2#54]
AbstractInstallSchema.php: line 72
`$cmsTableName = $this->getSetupConnection()->getTableName('cms_page');`
returns wrong table name if there are used tables with prefixes.

Can be changed to
`$cmsTableName = $this->setup->getTable('cms_page');`
but not sure if it is perfect solution

**Comment by vincenthornikx** [comment]
Fixed in 1.0.7
