### ISSUE TITLE
Setup script don't allow prefixed table names

### ISSUE THREAD

**Issue by JeroenBoersma** [Yoast/Yoast-SEO-for-Magento2#57]
The setup scripts won't work if the base tables are prefixed, I'm guessing hardcoded table names.

Didn't have time too look into this myself, but wanted to inform you guys :)

**Comment by vincenthornikx** [comment]
@JeroenBoersma the setup scripts use magento native table name resolving. Could you please try version 2.0.0 to see if this fixes your issue?
