### ISSUE TITLE
og:image meta is not showing for all images 

### ISSUE THREAD

**Issue by trushangsuthartri** [Yoast/Yoast-SEO-for-Magento2#60]
Hello 
I have installed this module on my magento 2 setup 
all og meta property is showing properly but 
og:image meta is not showing for all image on page

**Comment by vincenthornikx** [comment]
Hi @trushangsuthartri, I'm not sure what you mean. Is the og:image tag missing entirely or were you expecting extra og:image tags for all of the images on the page?

Regards,
Vincent
