### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by Stevie-Ray** [Yoast/Yoast-SEO-for-Magento2#64]
Please add support for PHP 7.1 by modifying the composer.json: add ~7.1.0

`    "require": {
        "php": "7.0.2|7.0.4|~7.0.6|~7.1.0",`

Magento stopped supporting PHP 5.6, so consider dropping: ~5.6.0

**Comment by vincenthornikx** [comment]
support for PHP 7.1 has been added in [1.1.2](https://github.com/Yoast/Yoast-SEO-for-Magento2/releases/tag/1.1.2)
