### ISSUE TITLE
Snippet preview always shows base URL of default store

### ISSUE THREAD

**Issue by peterjaap** [Yoast/Yoast-SEO-for-Magento2#65]
The nippet preview always shows the base URL of default store (with the url_key behind it of course), even though I am in a storeview where a different base URL is set.

**Comment by royvanos** [comment]
We're experiencing the same issue when editing category URLs, we've noticed this by editing a storeview that's not the default storeview. So, when editing the category URL key of storeview2.com, the snippet editor shows the URL of store1view.com (default store).

The URL gets saved to the correct storeview though, so it's not a huge problem, you just have to know that this is happening.

If you need any more information, please ask!

**Comment by vincenthornikx** [comment]
Confirmed. Will be fixed in the nexrt release.

**Comment by vincenthornikx** [comment]
@peterjaap @royvanos issue has been fixed in 2.0.0 version
