### ISSUE TITLE
Strict Mode

### ISSUE THREAD

**Issue by Joostdijck** [Yoast/Yoast-SEO-for-Magento2#66]
The plugin will not work in strict mode because "with(obj) {}"statement is being used in "yoast-seo.min.js"
in these places:
templates['assessmentPresenterResult'] line 13310
templates['hiddenSpan'] line 13378
templates['relevantWords'] line 13396
templates['snippetEditor'] line 13427

So either turn strict mode off for these functions, or rewrite the code so with (obj) statements are not used.

**Comment by vincenthornikx** [comment]
Hi @Joostdijck, I've notified the Yoast team about this. I'm afraid I can't fix this myself as the issue is in their codebase.

**Comment by vincenthornikx** [comment]
@Joostdijck according to the Yoast team this issue should be resolved now at their end. I have imported their latest libraries in the 2.0.0 release.
